### ISSUE TITLE
Directory_Сreator_By_List

### ISSUE THREAD

**Issue by xTarazTwilightForever** [xTarazTwilightForever/Twilight_Routine_Automation_Scripts#1]
Create a script that reads lists from the `Input_Files` folder and generates directories based on the names in these lists. Each directory should include a `.md` file to serve as a template for notes about completing each lesson from various courses.

## Tasks  
- [x] Read files from the `Input_Files` folder.  
- [x] Extract names from the lists to use as directory names.  
- [x] Create a directory for each name.  
- [x] Inside each directory, create a `.md` file with a predefined template.  
- [x] Ensure that all files are placed correctly in the appropriate directories.
